package com.dao;

import com.entity.power_predict_4h;

import java.util.Date;

public interface power_predict_4hMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_predict_4h
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_predict_4h
     *
     * @mbggenerated
     */
    int insert(power_predict_4h record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_predict_4h
     *
     * @mbggenerated
     */
    int insertSelective(power_predict_4h record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_predict_4h
     *
     * @mbggenerated
     */
    power_predict_4h selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_predict_4h
     *
     * @mbggenerated
     */
    power_predict_4h selectByTime(Date time);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_predict_4h
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(power_predict_4h record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_predict_4h
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(power_predict_4h record);
}