package com.dao;

import com.entity.user_event;
import com.service.HistorySearch.UserEventService;

import java.util.List;

public interface user_eventMapper {

    List<user_event>  selectUserEventByTime(UserEventService userEventTime);

    int selectAllUserEventByTime(UserEventService userEventTime);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_event
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_event
     *
     * @mbggenerated
     */
    int insert(user_event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_event
     *
     * @mbggenerated
     */
    int insertSelective(user_event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_event
     *
     * @mbggenerated
     */
    user_event selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(user_event record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_event
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(user_event record);
}