package com.entity;

import java.util.Date;

public class power_predict_4h {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.predict_time
     *
     * @mbggenerated
     */
    private Date predictTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.insert_time
     *
     * @mbggenerated
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v1
     *
     * @mbggenerated
     */
    private Float v1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v1_flag
     *
     * @mbggenerated
     */
    private Byte v1Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v2
     *
     * @mbggenerated
     */
    private Float v2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v2_flag
     *
     * @mbggenerated
     */
    private Byte v2Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v3
     *
     * @mbggenerated
     */
    private Float v3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v3_flag
     *
     * @mbggenerated
     */
    private Byte v3Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v4
     *
     * @mbggenerated
     */
    private Float v4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v4_flag
     *
     * @mbggenerated
     */
    private Byte v4Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v5
     *
     * @mbggenerated
     */
    private Float v5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v5_flag
     *
     * @mbggenerated
     */
    private Byte v5Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v6
     *
     * @mbggenerated
     */
    private Float v6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v6_flag
     *
     * @mbggenerated
     */
    private Byte v6Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v7
     *
     * @mbggenerated
     */
    private Float v7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v7_flag
     *
     * @mbggenerated
     */
    private Byte v7Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v8
     *
     * @mbggenerated
     */
    private Float v8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v8_flag
     *
     * @mbggenerated
     */
    private Byte v8Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v9
     *
     * @mbggenerated
     */
    private Float v9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v9_flag
     *
     * @mbggenerated
     */
    private Byte v9Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v10
     *
     * @mbggenerated
     */
    private Float v10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v10_flag
     *
     * @mbggenerated
     */
    private Byte v10Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v11
     *
     * @mbggenerated
     */
    private Float v11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v11_flag
     *
     * @mbggenerated
     */
    private Byte v11Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v12
     *
     * @mbggenerated
     */
    private Float v12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v12_flag
     *
     * @mbggenerated
     */
    private Byte v12Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v13
     *
     * @mbggenerated
     */
    private Float v13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v13_flag
     *
     * @mbggenerated
     */
    private Byte v13Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v14
     *
     * @mbggenerated
     */
    private Float v14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v14_flag
     *
     * @mbggenerated
     */
    private Byte v14Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v15
     *
     * @mbggenerated
     */
    private Float v15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v15_flag
     *
     * @mbggenerated
     */
    private Byte v15Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v16
     *
     * @mbggenerated
     */
    private Float v16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_predict_4h.v16_flag
     *
     * @mbggenerated
     */
    private Byte v16Flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.id
     *
     * @return the value of power_predict_4h.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.id
     *
     * @param id the value for power_predict_4h.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.predict_time
     *
     * @return the value of power_predict_4h.predict_time
     *
     * @mbggenerated
     */
    public Date getPredictTime() {
        return predictTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.predict_time
     *
     * @param predictTime the value for power_predict_4h.predict_time
     *
     * @mbggenerated
     */
    public void setPredictTime(Date predictTime) {
        this.predictTime = predictTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.insert_time
     *
     * @return the value of power_predict_4h.insert_time
     *
     * @mbggenerated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.insert_time
     *
     * @param insertTime the value for power_predict_4h.insert_time
     *
     * @mbggenerated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v1
     *
     * @return the value of power_predict_4h.v1
     *
     * @mbggenerated
     */
    public Float getV1() {
        return v1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v1
     *
     * @param v1 the value for power_predict_4h.v1
     *
     * @mbggenerated
     */
    public void setV1(Float v1) {
        this.v1 = v1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v1_flag
     *
     * @return the value of power_predict_4h.v1_flag
     *
     * @mbggenerated
     */
    public Byte getV1Flag() {
        return v1Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v1_flag
     *
     * @param v1Flag the value for power_predict_4h.v1_flag
     *
     * @mbggenerated
     */
    public void setV1Flag(Byte v1Flag) {
        this.v1Flag = v1Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v2
     *
     * @return the value of power_predict_4h.v2
     *
     * @mbggenerated
     */
    public Float getV2() {
        return v2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v2
     *
     * @param v2 the value for power_predict_4h.v2
     *
     * @mbggenerated
     */
    public void setV2(Float v2) {
        this.v2 = v2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v2_flag
     *
     * @return the value of power_predict_4h.v2_flag
     *
     * @mbggenerated
     */
    public Byte getV2Flag() {
        return v2Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v2_flag
     *
     * @param v2Flag the value for power_predict_4h.v2_flag
     *
     * @mbggenerated
     */
    public void setV2Flag(Byte v2Flag) {
        this.v2Flag = v2Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v3
     *
     * @return the value of power_predict_4h.v3
     *
     * @mbggenerated
     */
    public Float getV3() {
        return v3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v3
     *
     * @param v3 the value for power_predict_4h.v3
     *
     * @mbggenerated
     */
    public void setV3(Float v3) {
        this.v3 = v3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v3_flag
     *
     * @return the value of power_predict_4h.v3_flag
     *
     * @mbggenerated
     */
    public Byte getV3Flag() {
        return v3Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v3_flag
     *
     * @param v3Flag the value for power_predict_4h.v3_flag
     *
     * @mbggenerated
     */
    public void setV3Flag(Byte v3Flag) {
        this.v3Flag = v3Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v4
     *
     * @return the value of power_predict_4h.v4
     *
     * @mbggenerated
     */
    public Float getV4() {
        return v4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v4
     *
     * @param v4 the value for power_predict_4h.v4
     *
     * @mbggenerated
     */
    public void setV4(Float v4) {
        this.v4 = v4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v4_flag
     *
     * @return the value of power_predict_4h.v4_flag
     *
     * @mbggenerated
     */
    public Byte getV4Flag() {
        return v4Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v4_flag
     *
     * @param v4Flag the value for power_predict_4h.v4_flag
     *
     * @mbggenerated
     */
    public void setV4Flag(Byte v4Flag) {
        this.v4Flag = v4Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v5
     *
     * @return the value of power_predict_4h.v5
     *
     * @mbggenerated
     */
    public Float getV5() {
        return v5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v5
     *
     * @param v5 the value for power_predict_4h.v5
     *
     * @mbggenerated
     */
    public void setV5(Float v5) {
        this.v5 = v5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v5_flag
     *
     * @return the value of power_predict_4h.v5_flag
     *
     * @mbggenerated
     */
    public Byte getV5Flag() {
        return v5Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v5_flag
     *
     * @param v5Flag the value for power_predict_4h.v5_flag
     *
     * @mbggenerated
     */
    public void setV5Flag(Byte v5Flag) {
        this.v5Flag = v5Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v6
     *
     * @return the value of power_predict_4h.v6
     *
     * @mbggenerated
     */
    public Float getV6() {
        return v6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v6
     *
     * @param v6 the value for power_predict_4h.v6
     *
     * @mbggenerated
     */
    public void setV6(Float v6) {
        this.v6 = v6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v6_flag
     *
     * @return the value of power_predict_4h.v6_flag
     *
     * @mbggenerated
     */
    public Byte getV6Flag() {
        return v6Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v6_flag
     *
     * @param v6Flag the value for power_predict_4h.v6_flag
     *
     * @mbggenerated
     */
    public void setV6Flag(Byte v6Flag) {
        this.v6Flag = v6Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v7
     *
     * @return the value of power_predict_4h.v7
     *
     * @mbggenerated
     */
    public Float getV7() {
        return v7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v7
     *
     * @param v7 the value for power_predict_4h.v7
     *
     * @mbggenerated
     */
    public void setV7(Float v7) {
        this.v7 = v7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v7_flag
     *
     * @return the value of power_predict_4h.v7_flag
     *
     * @mbggenerated
     */
    public Byte getV7Flag() {
        return v7Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v7_flag
     *
     * @param v7Flag the value for power_predict_4h.v7_flag
     *
     * @mbggenerated
     */
    public void setV7Flag(Byte v7Flag) {
        this.v7Flag = v7Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v8
     *
     * @return the value of power_predict_4h.v8
     *
     * @mbggenerated
     */
    public Float getV8() {
        return v8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v8
     *
     * @param v8 the value for power_predict_4h.v8
     *
     * @mbggenerated
     */
    public void setV8(Float v8) {
        this.v8 = v8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v8_flag
     *
     * @return the value of power_predict_4h.v8_flag
     *
     * @mbggenerated
     */
    public Byte getV8Flag() {
        return v8Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v8_flag
     *
     * @param v8Flag the value for power_predict_4h.v8_flag
     *
     * @mbggenerated
     */
    public void setV8Flag(Byte v8Flag) {
        this.v8Flag = v8Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v9
     *
     * @return the value of power_predict_4h.v9
     *
     * @mbggenerated
     */
    public Float getV9() {
        return v9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v9
     *
     * @param v9 the value for power_predict_4h.v9
     *
     * @mbggenerated
     */
    public void setV9(Float v9) {
        this.v9 = v9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v9_flag
     *
     * @return the value of power_predict_4h.v9_flag
     *
     * @mbggenerated
     */
    public Byte getV9Flag() {
        return v9Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v9_flag
     *
     * @param v9Flag the value for power_predict_4h.v9_flag
     *
     * @mbggenerated
     */
    public void setV9Flag(Byte v9Flag) {
        this.v9Flag = v9Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v10
     *
     * @return the value of power_predict_4h.v10
     *
     * @mbggenerated
     */
    public Float getV10() {
        return v10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v10
     *
     * @param v10 the value for power_predict_4h.v10
     *
     * @mbggenerated
     */
    public void setV10(Float v10) {
        this.v10 = v10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v10_flag
     *
     * @return the value of power_predict_4h.v10_flag
     *
     * @mbggenerated
     */
    public Byte getV10Flag() {
        return v10Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v10_flag
     *
     * @param v10Flag the value for power_predict_4h.v10_flag
     *
     * @mbggenerated
     */
    public void setV10Flag(Byte v10Flag) {
        this.v10Flag = v10Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v11
     *
     * @return the value of power_predict_4h.v11
     *
     * @mbggenerated
     */
    public Float getV11() {
        return v11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v11
     *
     * @param v11 the value for power_predict_4h.v11
     *
     * @mbggenerated
     */
    public void setV11(Float v11) {
        this.v11 = v11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v11_flag
     *
     * @return the value of power_predict_4h.v11_flag
     *
     * @mbggenerated
     */
    public Byte getV11Flag() {
        return v11Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v11_flag
     *
     * @param v11Flag the value for power_predict_4h.v11_flag
     *
     * @mbggenerated
     */
    public void setV11Flag(Byte v11Flag) {
        this.v11Flag = v11Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v12
     *
     * @return the value of power_predict_4h.v12
     *
     * @mbggenerated
     */
    public Float getV12() {
        return v12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v12
     *
     * @param v12 the value for power_predict_4h.v12
     *
     * @mbggenerated
     */
    public void setV12(Float v12) {
        this.v12 = v12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v12_flag
     *
     * @return the value of power_predict_4h.v12_flag
     *
     * @mbggenerated
     */
    public Byte getV12Flag() {
        return v12Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v12_flag
     *
     * @param v12Flag the value for power_predict_4h.v12_flag
     *
     * @mbggenerated
     */
    public void setV12Flag(Byte v12Flag) {
        this.v12Flag = v12Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v13
     *
     * @return the value of power_predict_4h.v13
     *
     * @mbggenerated
     */
    public Float getV13() {
        return v13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v13
     *
     * @param v13 the value for power_predict_4h.v13
     *
     * @mbggenerated
     */
    public void setV13(Float v13) {
        this.v13 = v13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v13_flag
     *
     * @return the value of power_predict_4h.v13_flag
     *
     * @mbggenerated
     */
    public Byte getV13Flag() {
        return v13Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v13_flag
     *
     * @param v13Flag the value for power_predict_4h.v13_flag
     *
     * @mbggenerated
     */
    public void setV13Flag(Byte v13Flag) {
        this.v13Flag = v13Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v14
     *
     * @return the value of power_predict_4h.v14
     *
     * @mbggenerated
     */
    public Float getV14() {
        return v14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v14
     *
     * @param v14 the value for power_predict_4h.v14
     *
     * @mbggenerated
     */
    public void setV14(Float v14) {
        this.v14 = v14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v14_flag
     *
     * @return the value of power_predict_4h.v14_flag
     *
     * @mbggenerated
     */
    public Byte getV14Flag() {
        return v14Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v14_flag
     *
     * @param v14Flag the value for power_predict_4h.v14_flag
     *
     * @mbggenerated
     */
    public void setV14Flag(Byte v14Flag) {
        this.v14Flag = v14Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v15
     *
     * @return the value of power_predict_4h.v15
     *
     * @mbggenerated
     */
    public Float getV15() {
        return v15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v15
     *
     * @param v15 the value for power_predict_4h.v15
     *
     * @mbggenerated
     */
    public void setV15(Float v15) {
        this.v15 = v15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v15_flag
     *
     * @return the value of power_predict_4h.v15_flag
     *
     * @mbggenerated
     */
    public Byte getV15Flag() {
        return v15Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v15_flag
     *
     * @param v15Flag the value for power_predict_4h.v15_flag
     *
     * @mbggenerated
     */
    public void setV15Flag(Byte v15Flag) {
        this.v15Flag = v15Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v16
     *
     * @return the value of power_predict_4h.v16
     *
     * @mbggenerated
     */
    public Float getV16() {
        return v16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v16
     *
     * @param v16 the value for power_predict_4h.v16
     *
     * @mbggenerated
     */
    public void setV16(Float v16) {
        this.v16 = v16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_predict_4h.v16_flag
     *
     * @return the value of power_predict_4h.v16_flag
     *
     * @mbggenerated
     */
    public Byte getV16Flag() {
        return v16Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_predict_4h.v16_flag
     *
     * @param v16Flag the value for power_predict_4h.v16_flag
     *
     * @mbggenerated
     */
    public void setV16Flag(Byte v16Flag) {
        this.v16Flag = v16Flag;
    }
}